"""added created at to table payment

Revision ID: 1456a7900b5b
Revises: 7aabb890711b
Create Date: 2025-06-22 19:44:50.570843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1456a7900b5b'
down_revision = '7aabb890711b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
