"""added extra columns to orders table 

Revision ID: 213dcba2fb02
Revises: 41fc144f26e0
Create Date: 2025-06-08 10:16:07.599731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '213dcba2fb02'
down_revision = '41fc144f26e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fabric_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fabric_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('width', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_length_meters', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('delivery_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('design_specification', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('factory_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('print_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('lamination_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cut_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('label_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.alter_column('form_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('orders_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.drop_column('design_specs')
        batch_op.drop_column('status')
        batch_op.drop_column('created_by_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))
        batch_op.add_column(sa.Column('design_specs', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('orders_ibfk_1'), 'users', ['created_by_id'], ['id'])
        batch_op.alter_column('form_number',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False)
        batch_op.drop_column('created_by')
        batch_op.drop_column('label_type')
        batch_op.drop_column('cut_type')
        batch_op.drop_column('lamination_type')
        batch_op.drop_column('print_type')
        batch_op.drop_column('factory_notes')
        batch_op.drop_column('design_specification')
        batch_op.drop_column('delivery_date')
        batch_op.drop_column('total_length_meters')
        batch_op.drop_column('quantity')
        batch_op.drop_column('height')
        batch_op.drop_column('width')
        batch_op.drop_column('fabric_code')
        batch_op.drop_column('fabric_name')

    # ### end Alembic commands ###
