"""updated shift changing on machine

Revision ID: 4b900c31bc35
Revises: 9628572c552d
Create Date: 2025-06-11 10:49:18.310619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b900c31bc35'
down_revision = '9628572c552d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_name', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('remaining_quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('production_duration', sa.String(length=256), nullable=True))
        batch_op.drop_column('left_time_to_finish')
        batch_op.drop_column('left_count_to_finish')
        batch_op.drop_column('worder_name')
        batch_op.drop_column('start_count')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('production_duration', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('production_duration')

    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_count', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('worder_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True))
        batch_op.add_column(sa.Column('left_count_to_finish', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('left_time_to_finish', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('production_duration')
        batch_op.drop_column('remaining_quantity')
        batch_op.drop_column('end_time')
        batch_op.drop_column('worker_name')

    # ### end Alembic commands ###
