"""created work_statistics table 

Revision ID: 4e03c0dbf9d8
Revises: d862fadb6f87
Create Date: 2025-06-10 13:52:45.976671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e03c0dbf9d8'
down_revision = 'd862fadb6f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_stage', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('progress_percentage', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('progress_percentage')
        batch_op.drop_column('current_stage')

    # ### end Alembic commands ###
