"""removed invoiced from payment and added it to orders table 

Revision ID: 670569f90663
Revises: 9e2a31afbd56
Create Date: 2025-06-25 23:20:38.146487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '670569f90663'
down_revision = '9e2a31afbd56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoiced', sa.Boolean(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('invoiced')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoiced', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('invoiced')

    # ### end Alembic commands ###
