"""changed the type of peak_quantity

Revision ID: 7aabb890711b
Revises: f477fc5f824b
Create Date: 2025-06-22 19:37:23.365170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7aabb890711b'
down_revision = 'f477fc5f824b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('peak_quantity',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('peak_quantity',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
