"""add is_active column to users table

Revision ID: 89919eccddcb
Revises: 60908540707f
Create Date: 2025-06-07 13:35:01.251413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89919eccddcb'
down_revision = '60908540707f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
