"""added shift type column

Revision ID: 9628572c552d
Revises: c5fc35693ca5
Create Date: 2025-06-11 10:15:11.210589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9628572c552d'
down_revision = 'c5fc35693ca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift_type', sa.Enum('day', 'night', name='shift_type_enum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_column('shift_type')

    # ### end Alembic commands ###
