"""added few column to invoice table 

Revision ID: 975cdca27a72
Revises: e8babe172f17
Create Date: 2025-06-11 16:33:02.771970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975cdca27a72'
down_revision = 'e8babe172f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('tax', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('tax')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
