"""removed columns on orders table 

Revision ID: b6c7bfaf61c9
Revises: 4e03c0dbf9d8
Create Date: 2025-06-10 14:35:05.225407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6c7bfaf61c9'
down_revision = '4e03c0dbf9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('current_stage')
        batch_op.drop_column('progress_percentage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress_percentage', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('current_stage', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))

    # ### end Alembic commands ###
