"""updated machine table 

Revision ID: bb3d9938e40f
Revises: 4b900c31bc35
Create Date: 2025-06-11 10:57:06.808035

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb3d9938e40f'
down_revision = '4b900c31bc35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_column('production_duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('production_duration', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True))

    # ### end Alembic commands ###
