"""added machine table

Revision ID: c5fc35693ca5
Revises: db47d3dbefe4
Create Date: 2025-06-11 09:56:46.401336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5fc35693ca5'
down_revision = 'db47d3dbefe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_statistics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_statistics',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('roll_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('meterage', mysql.FLOAT(), nullable=True),
    sa.Column('pack_count_1', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pack_amount_1', mysql.FLOAT(), nullable=True),
    sa.Column('pack_count_2', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pack_amount_2', mysql.FLOAT(), nullable=True),
    sa.Column('pack_count_3', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pack_amount_3', mysql.FLOAT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('work_statistics_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
