"""removed fabric_name

Revision ID: d28d0b13dfd2
Revises: 5938a99d4c2c
Create Date: 2025-06-09 11:35:14.495773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd28d0b13dfd2'
down_revision = '5938a99d4c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fabric_density', sa.Integer(), nullable=True))
        batch_op.drop_column('fabric_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fabric_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
        batch_op.drop_column('fabric_density')

    # ### end Alembic commands ###
