"""changed column name from orders

Revision ID: d862fadb6f87
Revises: fcf76428d6d4
Create Date: 2025-06-09 13:48:28.579975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd862fadb6f87'
down_revision = 'fcf76428d6d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fusing_type', sa.String(length=50), nullable=True))
        batch_op.drop_column('print_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('print_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
        batch_op.drop_column('fusing_type')

    # ### end Alembic commands ###
