"""added some columns to order table

Revision ID: db47d3dbefe4
Revises: b6c7bfaf61c9
Create Date: 2025-06-10 15:43:30.646285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db47d3dbefe4'
down_revision = 'b6c7bfaf61c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_stage', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('progress_percentage', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('progress_percentage')
        batch_op.drop_column('current_stage')

    # ### end Alembic commands ###
