"""added production_step_log table 

Revision ID: e8babe172f17
Revises: update_shift_type_to_lowercase
Create Date: 2025-06-11 12:46:11.140559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8babe172f17'
down_revision = 'update_shift_type_to_lowercase'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_step_log', schema=None) as batch_op:
        batch_op.alter_column('step_name',
               existing_type=mysql.ENUM('MONGANE', 'AHAR', 'PRESS', 'BRESH', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('MONGANE', 'AHAR', 'PRESS', 'BRESH', name='production_step_enum', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_step_log', schema=None) as batch_op:
        batch_op.alter_column('step_name',
               existing_type=sa.Enum('MONGANE', 'AHAR', 'PRESS', 'BRESH', name='production_step_enum', native_enum=False),
               type_=mysql.ENUM('MONGANE', 'AHAR', 'PRESS', 'BRESH', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)

    # ### end Alembic commands ###
