"""adding correct columns to payment table

Revision ID: f477fc5f824b
Revises: ddac23400ba9
Create Date: 2025-06-22 16:12:24.419674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f477fc5f824b'
down_revision = 'ddac23400ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_card', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('number_of_cuts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('number_of_density', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('peak_quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('peak_width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('Fee', sa.Integer(), nullable=True))
        batch_op.drop_column('discount')
        batch_op.drop_column('tax')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
        batch_op.add_column(sa.Column('tax', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('discount', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('Fee')
        batch_op.drop_column('peak_width')
        batch_op.drop_column('peak_quantity')
        batch_op.drop_column('number_of_density')
        batch_op.drop_column('number_of_cuts')
        batch_op.drop_column('credit_card')

    # ### end Alembic commands ###
