"""removed fabric_code

Revision ID: fcf76428d6d4
Revises: d28d0b13dfd2
Create Date: 2025-06-09 11:40:25.138856

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fcf76428d6d4'
down_revision = 'd28d0b13dfd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fabric_cut', sa.Integer(), nullable=True))
        batch_op.drop_column('fabric_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fabric_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
        batch_op.drop_column('fabric_cut')

    # ### end Alembic commands ###
